### ISSUE TITLE
Todo Script : problem of comparaison

### ISSUE THREAD

**Issue by caouecs** [Laravel-Lang/lang#1589]
- Laravel-Lang Version: 8.1.0
- PHP Version: n/a => Github Actions

### Description:

For the Todo script, in French ( but I think it's same for other languages ), it has problem with accent and spaces.

For it, "Réunion" and "Reunion" are same, like "Aland Islands" and "Åland Islands"

We have the same problem with : "Lao People's Democratic Republic" and "Laos"

https://github.com/Laravel-Lang/lang/blob/master/todo/fr.md

### Steps To Reproduce:

 * reload todo for French translations

**Comment by andrey-helldar** [comment]
Got it. I will solve this problem.

**Comment by andrey-helldar** [comment]
I submitted a PR. Added check strict.

**Comment by andrey-helldar** [comment]
@caouecs, if I understood correctly, the problem was typing - it was not strict:

```php
protected function hasExclude(string $key, string $locale): bool
{
    return in_array($key, $this->getExcludes($locale)) || in_array($key, $this->getExcludes());
}
```

I replaced the check with strict:

```php
protected function hasExclude(string $key, string $locale): bool
{
    return in_array($key, $this->getExcludes($locale), true) || in_array($key, $this->getExcludes(), true);
}
```

Currently, the key translation for [Iran](https://github.com/Laravel-Lang/lang/blob/master/script/en/en.json#L254) is included in the [docs/statuses/fr.md](https://github.com/Laravel-Lang/lang/blob/master/docs/statuses/fr.md) file because it is not excluded from processing: [excludes/_all.php](https://github.com/Laravel-Lang/lang/blob/master/excludes/_all.php) and [excludes/fr.php](https://github.com/Laravel-Lang/lang/blob/master/excludes/fr.php).
