### ISSUE TITLE
Some translations have been lost in the new version (10.0)

### ISSUE THREAD

**Issue by luisprmat** [Laravel-Lang/lang#1761]
- Laravel-Lang Version: 10.0.1
- PHP Version: 8.0.3

### Description:
Using the translations in a new project I was able to observe that some translations that were already correct **have been lost**.

![Captura](https://user-images.githubusercontent.com/9275870/119599372-7e8a1280-bdaa-11eb-8390-36d8e807d5e7.PNG)

Some of them are:

- [Reset Password Notification](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Auth/Notifications/ResetPassword.php#L87)
- [You are receiving this email because we received a password reset request for your account.](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Auth/Notifications/ResetPassword.php#L88)
- [If you did not request a password reset, no further action is required.](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Auth/Notifications/ResetPassword.php#L91)
- [All rights reserved.](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Mail/resources/views/html/message.blade.php#L24)

The above translations were present in the **version 9.1.2** in [`source/en.json`](https://github.com/Laravel-Lang/lang/blob/9.1.2/source/en.json) 

Everything seems to indicate that they are the translations wrapped in `Lang::get('...')` and `@lang` directive that I referred to in [this comment](https://github.com/Laravel-Lang/lang/pull/1748#issuecomment-840874598)

### Steps To Reproduce:

- Install a new laravel project with a [starter kit](https://laravel.com/docs/8.x/starter-kits)
- Set some language
- Send a reset password email

**Comment by caouecs** [comment]
I will do a check too

**Comment by andrey-helldar** [comment]
I thought it seemed to me :-)

In the near future I will check and will check the keys from the previous version.

**Comment by andrey-helldar** [comment]
@luisprmat, @caouecs, I know why this happened:

**v9.1.1:**
![image](https://user-images.githubusercontent.com/10347617/119710070-9a52ee80-be66-11eb-9c65-ad85c4d97891.png)

**v10.0.1:**
![image](https://user-images.githubusercontent.com/10347617/119710159-b6ef2680-be66-11eb-8fe4-41f604672696.png)

The locale.json file splitting script works like this:
1. The contents of the `locale.json` file are loaded into a variable;
2. The file for splitting is loaded, for example, `nova.json`;
3. From the source file we take only those keys that are in the `nova.json` file;
4. Replace the keys in the `nova.json` file with the original ones;
5. Save the `nova.json` file;
6. We process all other files in the same way;
7. When finished, we get a list of all keys from the split files;
8. From the main file, delete the keys used in the packages;
9. Save the original file with the remaining keys.

The script removes lines like [Reset Password Notification](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Auth/Notifications/ResetPassword.php#L87), since it is already used in `nova.json`.

The problem is that the Laravel framework does not have a [json file](https://github.com/laravel/laravel/tree/8.x/resources/lang) with translations.

Therefore, we do not know what keys should be left in the `locale.json` file.

What you can do: now we have a script that scans Jetstream and Fortify projects, collects keys from them for translations and saves them to files.
I can load the Laravel Framework dependencies and do the same with it.
At the moment, this is the only option to get a complete list of these keys, since the script does not know which keys it needs to recover.

Another option: I can find all translation keys, save them to a file and merge them with the current files. It will be the same, but the project will not need to be installed when running phpunit and deploying the project locally.

**Comment by andrey-helldar** [comment]
I know how to solve this problem.

A little later we will create a PR.

**Comment by andrey-helldar** [comment]
Hm...

![image](https://user-images.githubusercontent.com/10347617/119713855-db4d0200-be6a-11eb-9a6c-f4d7be8817df.png)

![image](https://user-images.githubusercontent.com/10347617/119713911-e99b1e00-be6a-11eb-911a-e75d65e6426e.png)

**Comment by andrey-helldar** [comment]
For example, the `Oh no` key was added in version 4.0 and it is not known which package it belongs to, since it was in version 4.0 that the json file was first published.

![image](https://user-images.githubusercontent.com/10347617/119714802-f2402400-be6b-11eb-83bb-97bca34e0775.png)

![image](https://user-images.githubusercontent.com/10347617/119714817-f66c4180-be6b-11eb-995b-2126860f6e0d.png)

**Comment by andrey-helldar** [comment]
Laravel 5.7: https://github.com/Laravel-Lang/lang/commit/8a4775478a0431446b56fef0c6d6d606aa61b848

![image](https://user-images.githubusercontent.com/10347617/119715501-be193300-be6c-11eb-8ba7-53dbf3746441.png)

Laravel 8 does not contain these keys.

@caouecs, what do we do?

**Comment by andrey-helldar** [comment]
I suggest the following option: in this repository, we will only store the most recent state of the translation keys.

If someone needs to use translations for older versions of Laravel, they can either install the old dependency of that package or use translation managers, for example: [compatibility table](https://andrey-helldar.github.io/laravel-lang-publisher/compatibility.html).

**Comment by luisprmat** [comment]
`Oh no` appears in [this view](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Exceptions/views/illustrated-layout.blade.php#L464) in Laravel 8.

**Comment by andrey-helldar** [comment]
> `Oh no` appears in [this view](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Exceptions/views/illustrated-layout.blade.php#L464) in Laravel 8.

Yes, I have already found and deleted my unnecessary messages 😅

**Comment by andrey-helldar** [comment]
Lol https://github.com/laravel/framework/blob/8.x/src/Illuminate/Notifications/resources/views/email.blade.php#L53-L59 )))

![image](https://user-images.githubusercontent.com/10347617/119723134-cc1f8180-be75-11eb-9132-1c719e5c0b70.png)

**Comment by andrey-helldar** [comment]
I will do this:

1. Automatic search found translation keys;
2. Next, I will manually look at the framework files and find multi-line keys;
3. I will add these keys to the translation file;
4. Disable automatic search for keys in the framework;
5. I will copy the files from version 9;
6. Run a script that will find the translated keys for each localization from the old files and save them to the new ones;
7. I will transfer https://github.com/Laravel-Lang/lang/pull/1762 to the status "ready".

**Comment by andrey-helldar** [comment]
Current state after searching for keys in `laravel/framework` project:

![image](https://user-images.githubusercontent.com/10347617/119724349-47356780-be77-11eb-8b96-e4d04cd4f3f1.png)

**Comment by luisprmat** [comment]
Are they not very few?  About these?

- [Toggle navigation](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Auth/Console/stubs/make/views/layouts/app.stub#L29)
- [Login](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Auth/Console/stubs/make/views/layouts/app.stub#L44)
- [Register](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Auth/Console/stubs/make/views/layouts/app.stub#L48)

We must bear in mind that some translations do not wrap strings directly but rather variables that contain strings. For example:
- [This action is unauthorized.](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Auth/Access/AuthorizationException.php#L27) is passed to the `$message` variable through the constructor method (**line 27**) and later translated from [this view](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Exceptions/views/403.blade.php#L5) (**line 5**) `__($exception->getMessage() ?: 'Forbidden')`

Since these strings it was always possible to translate them from previous versions I don't see why now they should disappear

**Comment by andrey-helldar** [comment]
@luisprmat, should not.

The problem is that we have added translation keys nova, jetstream, fortify and others to one file.

From a code point of view, after splitting a file, it is not known which keys should remain in the main file.

This is precisely the current problem.

The screenshot above is what the parser was able to find.

This is why I will manually search for other translation keys in order to recreate the original file.

Only after that I will restore the translation of the lines that were lost during the upgrade from 9 to 10 version.

**Comment by ottenso** [comment]
Hey @andrey-helldar,

did I understand correctly that the error occurred only when splitting the files (from V9 to V10) and when adding new packages that also have duplicates to other packages, this error will not occur in the future? When adding new packages, the error with duplicates should not occur.

Wouldn't it be easier to optimize the splitting script (applied to V9) and apply it again to V9 (with subsequent merge to V10)? Just a quick thought from me, without understanding exactly what happened.

**Comment by andrey-helldar** [comment]
@ottenso, yes it is a separation problem. I'm working on it.

**Comment by andrey-helldar** [comment]
The easiest way is to return the state of the files before we added the Nova and Jetstream translations to it.
