### ISSUE TITLE
why is laravel-lang/publisher required

### ISSUE THREAD

**Issue by Jimbolino** [Laravel-Lang/lang#2954]
### Feature description

Why is laravel-lang/publisher required now?
because laravel-lang/publisher depends on dragon-code/support, which requires ext-bcmath

why not keep this optional or require-dev ?

### Environment

- Laravel-Lang Version: latest
- Laravel Version: latest
- PHP Version: latest

**Comment by Jimbolino** [comment]
you could just symlink the relevant json files right?

**Comment by andrey-helldar** [comment]
We can't do that because the structure of the files in the package doesn't match the structure of the files in the application.

Our files:
```
{locale}
  php.json
  php-inline.json
  json.json
  json-inline.json
```

Our files:
```
{locale}
  php.json
  php-inline.json
  json.json
  json-inline.json
```

Application files:
```
{locale}
  auth.php
  pagination.php
  passwords.php
  validation.php
{locale}.json
```

In addition, the files from the [Lang](https://github.com/Laravel-Lang/lang) project contain translations not only of the framework, but also of other [Laravel packages](https://github.com/Laravel-Lang/lang/tree/main/source). The files contain not just translations from different packages, but also from different versions of the same package.

When installing and updating translations, the publisher determines which of the packages are installed and adds keys to the project only for them.

So no, the symlink won't work.

**Comment by andrey-helldar** [comment]
And answering the very first question from the title, I’ll say that by adding the publisher to the mandatory installation, we thus standardized all our projects. In addition, at the moment there are no other installers for these files, as we are constantly improving the structure of the project and not everyone has time to update it, despite the fact that we release it only when the publisher is definitely working.

**Comment by Jimbolino** [comment]
I assumed the main reason you switched from php to json was because the default laravel skeleton doesn't include the php file anymore (by default), and they added json support.

But now i've looked more closely at the package, and it does a lot more then what it did before :)
(i've been using this package since the Laravel 4.2 days)

Maybe a bit too late, but a changelog/upgrade guide would have been nice, at least for upgrading between the major versions :)

Thnx for the quick responses :+1:

**Comment by andrey-helldar** [comment]
We've had a changelog on the site for a while, but it's mostly about which localizations have been translated. The same information is provided in the [release notes](https://github.com/Laravel-Lang/lang/releases) on GitHub. We just duplicated it on the site.

As for the upgrade guide, it is quite simple: https://laravel-lang.com/installation/upgrade-guide/

I think we can expand this section of the site soon. The old version of the documentation is still available here: https://github.com/Laravel-Lang/publisher/blob/main/docs/installation/index.md

**Comment by andrey-helldar** [comment]
Well, I never used symlinks unless they were referring to the storage folder 🙂

And so the Publisher project has existed for 5 years now. I started developing it when the Lang package was called `caouecs/laravel-lang` and had version 3 in release.
