### ISSUE TITLE
parameter `:attribute` in `de` is sometimes translated as `:Attribute`

### ISSUE THREAD

**Issue by DeepDiver1975** [Laravel-Lang/lang#3600]
### Environment

- Laravel-Lang Version: 13.2.2
- Laravel Version: 10.21
- PHP Version: 8.1.22

### Issue description

https://github.com/Laravel-Lang/lang/blob/bbef7ad051664626373ab68628676f140b2ec733/locales/de/php.json#L2

### Steps to reproduce

Look at the GitHub link ;-)

**Comment by DeepDiver1975** [comment]
same on `cs` 

https://github.com/Laravel-Lang/lang/blob/bbef7ad051664626373ab68628676f140b2ec733/locales/cs/php.json#L2

**Comment by DeepDiver1975** [comment]
Please ignore - I missed laravel capitalisation :see_no_evil:

**Comment by andrey-helldar** [comment]
Despite the found solution to the problem, I will still post my answer:

This behavior is by design since sentences must always start with a capital letter.

[Here](https://github.com/Laravel-Lang/common/discussions/7) you can also read how Laravel handles `:attribute`, `:Attribute` and `:ATTRIBUTE`.

Yes, the original file says `:attribute`, but that's because the sentence starts with "The":

https://github.com/Laravel-Lang/lang/blob/bbef7ad051664626373ab68628676f140b2ec733/source/framework/10.x/validation.php#L6

**Comment by DeepDiver1975** [comment]
Thanks for the answer! It might also help others running into this. 👍
